"""
report.py - Reporting Module
Aggregates findings from all scan modules into a single, timestamped
report (.txt or .html) with severity breakdown and a summary count.
"""

import os
import datetime

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info"]


def _severity_counts(findings):
    counts = {s: 0 for s in SEVERITY_ORDER}
    for f in findings:
        sev = f.get("severity", "Info")
        if sev in counts:
            counts[sev] += 1
    return counts


def generate_txt_report(target, all_findings, output_dir="reports"):
    """
    all_findings: dict like {"Security Headers": [...], "Cookies": [...], ...}
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_target = target.replace("https://", "").replace("http://", "").replace("/", "_")
    filename = os.path.join(output_dir, f"webguard_{safe_target}_{timestamp}.txt")

    flat = [f for group in all_findings.values() for f in group]
    counts = _severity_counts(flat)

    with open(filename, "w", encoding="utf-8") as f:
        f.write("=" * 60 + "\n")
        f.write("        WebGuard - Web Vulnerability Scan Report\n")
        f.write("=" * 60 + "\n")
        f.write(f"Target:    {target}\n")
        f.write(f"Scanned:   {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("-" * 60 + "\n")
        f.write("Severity Summary:\n")
        for sev in SEVERITY_ORDER:
            f.write(f"  {sev:<10}: {counts[sev]}\n")
        f.write("=" * 60 + "\n\n")

        for module_name, findings in all_findings.items():
            f.write(f"[{module_name}]\n")
            f.write("-" * 60 + "\n")
            if not findings:
                f.write("  No findings.\n\n")
                continue
            for item in findings:
                f.write(f"  Severity : {item.get('severity')}\n")
                f.write(f"  Check    : {item.get('check')}\n")
                f.write(f"  Status   : {item.get('status')}\n")
                f.write(f"  Detail   : {item.get('detail')}\n")
                f.write("  " + "-" * 40 + "\n")
            f.write("\n")

        f.write("=" * 60 + "\n")
        f.write("End of Report - Generated by WebGuard\n")

    print(f"\n[+] Report saved to: {filename}")
    return filename


def generate_html_report(target, all_findings, output_dir="reports"):
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_target = target.replace("https://", "").replace("http://", "").replace("/", "_")
    filename = os.path.join(output_dir, f"webguard_{safe_target}_{timestamp}.html")

    flat = [f for group in all_findings.values() for f in group]
    counts = _severity_counts(flat)

    severity_colors = {
        "Critical": "#8B0000", "High": "#D9534F", "Medium": "#E0A800",
        "Low": "#5BC0DE", "Info": "#6C757D",
    }

    rows = ""
    for module_name, findings in all_findings.items():
        rows += f"<h2>{module_name}</h2>"
        if not findings:
            rows += "<p><em>No findings.</em></p>"
            continue
        rows += "<table><tr><th>Severity</th><th>Check</th><th>Status</th><th>Detail</th></tr>"
        for item in findings:
            color = severity_colors.get(item.get("severity"), "#333")
            rows += (
                f"<tr><td style='color:{color};font-weight:bold'>{item.get('severity')}</td>"
                f"<td>{item.get('check')}</td><td>{item.get('status')}</td><td>{item.get('detail')}</td></tr>"
            )
        rows += "</table>"

    summary_html = "".join(
        f"<span class='badge' style='background:{severity_colors[s]}'>{s}: {counts[s]}</span>"
        for s in SEVERITY_ORDER
    )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>WebGuard Report - {target}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
h1 {{ color: #1F4E5F; }}
h2 {{ color: #1F4E5F; border-bottom: 2px solid #1F4E5F; padding-bottom: 4px; margin-top: 30px; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 14px; }}
th {{ background: #1F4E5F; color: white; }}
tr:nth-child(even) {{ background: #f7f9fa; }}
.badge {{ color: white; padding: 4px 10px; border-radius: 4px; margin-right: 8px; font-size: 13px; }}
.meta {{ color: #666; margin-bottom: 20px; }}
</style></head>
<body>
<h1>WebGuard - Web Vulnerability Scan Report</h1>
<p class="meta">Target: <strong>{target}</strong><br>
Scanned: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
<div>{summary_html}</div>
{rows}
<hr><p class="meta">Generated by WebGuard - for authorized security testing only.</p>
</body></html>"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"[+] HTML report saved to: {filename}")
    return filename
